name: Auto Release Package

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest git tag
        run: echo "::set-output name=lasttag::$(git describe --abbrev=0)"
        id: get-latest-tag
        shell: bash
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ (contains(github.ref_name, 'pre') || contains(steps.get-latest-tag.outputs.lasttag, 'pre')) && true || false }}
          tag_name: ${{ github.ref_name || steps.get-latest-tag.outputs.lasttag }}
          generate_release_notes: true
